on:
  issues:
    types:
      - opened

# Issue event types: https://docs.github.com/en/rest/overview/issue-event-types?apiVersion=2022-11-28
jobs:
  auto_triage_issue:
    uses: moxious/chatgpt-cli-action/.github/workflows/label-issue.yml@main
    with:
      url: ${{ github.event.issue.html_url }}
      type: issue
      prompt: "
        type/bug
        type/feature
        type/unknown
        type/other
        type/question
        type/duplicate
        type/invalid
        type/wonfix
        type/helpwanted
        area/frontend
        area/backend
        area/docs
        area/unknown
        area/other"
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GH_TOKEN: ${{ secrets.TOKEN }}
    
