on:
  issues:
    types:
      - opened

# Issue event types: https://docs.github.com/en/rest/overview/issue-event-types?apiVersion=2022-11-28
jobs:
  ta:
    uses: moxious/chatgpt-cli-action/.github/workflows/main.yml@main
    with:
      url: ${{ github.event.issue.html_url }}
      type: issue
      promp: "summarize the issue"

    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GH_TOKEN: ${{ secrets.TOKEN }}
