on:
  issues:
    types:
      - opened

# Issue event types: https://docs.github.com/en/rest/overview/issue-event-types?apiVersion=2022-11-28
jobs:
  ta:
    uses: moxious/chatgpt-cli-action/.github/workflows/main.yml@test_action_job
    with:
      url: ${{ github.event.issue.html_url }}
      type: issue
      promp: "summarize the issue"

    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GH_TOKEN: ${{ secrets.TOKEN }}

  triage_issue:
    runs-on: ubuntu-latest
    name: Triage issue
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          repostory: moxious/chatgpt-cli-action
          path: chatgpt-cli-action
      - name: Auto Label Issue
        uses: moxious/chatgpt-cli-action/.github/workflows/main.yml
        id: auto_label
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            GH_TOKEN: ${{ secrets.TOKEN }}
        with:
          url: https://github.com/grafana/grafana/issues/77598
          type: issue
          prompt: "
            I want you to help me apply the right GitHub label to an issue, and help me generate a summary of that issue.
            Ensure your response is syntactically valid JSON.  Output one object with three keys, type, area, and summary.
            The type and area keys can be JSON arrays of 1 or more choices of labels from the sets below. The summary
            must be a single string.

            You may choose more than one label for type and area, as a JSON array of strings, but only one summary
            string.
              
            Here is the list of type labels, please choose a type label only from this list:
              type/uncertain
              type/accessibility
              type/angular-2-react
              type/browser-compatibility
              type/bug
              type/build-packaging
              type/chore
              type/ci
              type/cleanup
              type/codegen
              type/community
              type/debt
              type/design
              type/discussion
              type/docs
              type/duplicate
              type/e2e
              type/epic
              type/feature-request
              type/feature-toggle-enable
              type/feature-toggle-removal
              type/performance
              type/poc
              type/project
              type/proposal
              type/question
              type/refactor
              type/regression
              type/roadmap
              type/tech
              type/ux

            Here is the list of area labels, please choose an area label only from this list:
              area/uncertain
              area/admin/user
              area/alerting
              area/alerting-legacy
              area/alerting/compliance
              area/alerting/evaluation
              area/alerting/notifications
              area/alerting/screenshots
              area/annotations
              area/auth
              area/auth/authproxy
              area/auth/ldap
              area/auth/oauth
              area/auth/rbac
              area/auth/saml
              area/auth/serviceaccount
              area/backend
              area/backend/api
              area/backend/config
              area/backend/db
              area/backend/db/migration
              area/backend/db/mysql
              area/backend/db/postgres
              area/backend/db/sql
              area/backend/db/sqlite
              area/backend/logging
              area/backend/plugins
              area/backend/security
              area/backend/user
              area/backend_srv
              area/configuration
              area/dashboard
              area/dashboard/data-links
              area/dashboard/drag-n-drop
              area/dashboard/folders
              area/dashboard/history
              area/dashboard/import
              area/dashboard/links
              area/dashboard/previews
              area/dashboard/rows
              area/dashboard/schemas
              area/dashboard/scripted
              area/dashboard/snapshot
              area/dashboard/templating
              area/dashboard/timerange
              area/dashboard/timezone
              area/dashboards/panel
              area/dashgpt
              area/data/export
              area/dataframe
              area/dataplane
              area/datasource
              area/datasource/backend
              area/datasource/frontend
              area/datasource/proxy
              area/dataviz
              area/developer-portal
              area/devenv
              area/docker
              area/drag-n-drop
              area/editor
              area/explore
              area/expressions
              area/field/overrides
              area/frontend
              area/frontend/code-editor
              area/frontend/library-panels
              area/frontend/library-variables
              area/frontend/login
              area/generativeAI
              area/glue
              area/grafana-cli
              area/grafana.com
              area/grafana/data
              area/grafana/e2e
              area/grafana/runtime
              area/grafana/toolkit
              area/grafana/ui
              area/grpc-server
              area/http-server
              area/image-rendering
              area/imagestore
              area/instrumentation
              area/internationalization
              area/kindsys
              area/legend
              area/libraries
              area/live
              area/logs
              area/mailing
              area/manage-dashboards
              area/meta-analytics
              area/mobile-support
              area/navigation
              area/panel-chrome
              area/panel/alertlist
              area/panel/annotation-list
              area/panel/barchart
              area/panel/bargauge
              area/panel/candlestick
              area/panel/canvas
              area/panel/common
              area/panel/dashboard-list
              area/panel/data
              area/panel/datagrid
              area/panel/edit
              area/panel/flame-graph
              area/panel/gauge
              area/panel/geomap
              area/panel/graph
              area/panel/heatmap
              area/panel/histogram
              area/panel/icon
              area/panel/infrastructure
              area/panel/logs
              area/panel/news
              area/panel/node-graph
              area/panel/piechart
              area/panel/singlestat
              area/panel/stat
              area/panel/state-timeline
              area/panel/status-history
              area/panel/support
              area/panel/table
              area/panel/text
              area/panel/timeseries
              area/panel/traceview
              area/panel/trend
              area/panel/xychart
              area/permissions
              area/playlist
              area/plugin-extensions
              area/plugins
              area/plugins-catalog
              area/plugins/app
              area/plugins/sandbox
              area/profiling
              area/provisioning
              area/public-dashboards
              area/query-editor
              area/recorded-queries
              area/resourcepicker
              area/reusable-queries
              area/routing
              area/scenes
              area/schema
              area/search
              area/security
              area/short-url
              area/shortcuts
              area/stack
              area/storybook
              area/streaming
              area/teams
              area/templating/repeating
              area/text-formatting
              area/thema
              area/tooltip
              area/tracing
              area/transformations
              area/ui/theme
              area/units
              area/ux
              area/value-mapping
            "
      - name: Output 
        run: echo "${{ steps.auto_label.outputs.output }}"
      - name: Errors 
        run: echo '${{ steps.auto_label.outputs.errors }}'