on:
  issues:
    types:
      - opened

# Issue event types: https://docs.github.com/en/rest/overview/issue-event-types?apiVersion=2022-11-28
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ID: ${{ github.event.issue.id }}
          NODE_ID: ${{ github.event.issue.node_id }}
          URL: ${{ github.event.issue.url }}}
          ACTOR: ${{ github.event.issue.actor }}
          EVENT: ${{ github.event.issue.event }}
          COMMIT_ID: ${{ github.event.issue.commit_id }}
          COMMIT_URL: ${{ github.event.issue.commit_url }}
          CREATED_AT: ${{ github.event.issue.created_at }}          
        run: |
          env | sort | grep -v TOKEN
          pip install git+https://github.com/marcolardera/chatgpt-cli

          echo "
            You will assist by taking the input I give you, and outputting the number of characters in the input.
          " > context.txt

          gh issue view $ISSUE_URL | chatgpt-cli --context ./context.txt
          gh issue edit $ISSUE_URL --add-label "triage"